/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  isProgramError,
  type Address,
  type SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM,
  type SolanaError,
} from "@solana/kit";
import { VAULT_PROGRAM_ADDRESS } from "../programs";

/** VaultAlreadyExists: Vault already exists */
export const VAULT_ERROR__VAULT_ALREADY_EXISTS = 0x1770; // 6000
/** InvalidAmount: Invalid amount */
export const VAULT_ERROR__INVALID_AMOUNT = 0x1771; // 6001
/** OutOfRange: Hunter is out of range */
export const VAULT_ERROR__OUT_OF_RANGE = 0x1772; // 6002
/** InvalidAuthority: Invalid backend authority */
export const VAULT_ERROR__INVALID_AUTHORITY = 0x1773; // 6003
/** CampaignFinished: Campaign has finished */
export const VAULT_ERROR__CAMPAIGN_FINISHED = 0x1774; // 6004
/** AlreadyClaimed: Hunter has already claimed this drop */
export const VAULT_ERROR__ALREADY_CLAIMED = 0x1775; // 6005
/** InvalidClaimRecord: Invalid claim record PDA */
export const VAULT_ERROR__INVALID_CLAIM_RECORD = 0x1776; // 6006

export type VaultError =
  | typeof VAULT_ERROR__ALREADY_CLAIMED
  | typeof VAULT_ERROR__CAMPAIGN_FINISHED
  | typeof VAULT_ERROR__INVALID_AMOUNT
  | typeof VAULT_ERROR__INVALID_AUTHORITY
  | typeof VAULT_ERROR__INVALID_CLAIM_RECORD
  | typeof VAULT_ERROR__OUT_OF_RANGE
  | typeof VAULT_ERROR__VAULT_ALREADY_EXISTS;

let vaultErrorMessages: Record<VaultError, string> | undefined;
if (process.env.NODE_ENV !== "production") {
  vaultErrorMessages = {
    [VAULT_ERROR__ALREADY_CLAIMED]: `Hunter has already claimed this drop`,
    [VAULT_ERROR__CAMPAIGN_FINISHED]: `Campaign has finished`,
    [VAULT_ERROR__INVALID_AMOUNT]: `Invalid amount`,
    [VAULT_ERROR__INVALID_AUTHORITY]: `Invalid backend authority`,
    [VAULT_ERROR__INVALID_CLAIM_RECORD]: `Invalid claim record PDA`,
    [VAULT_ERROR__OUT_OF_RANGE]: `Hunter is out of range`,
    [VAULT_ERROR__VAULT_ALREADY_EXISTS]: `Vault already exists`,
  };
}

export function getVaultErrorMessage(code: VaultError): string {
  if (process.env.NODE_ENV !== "production") {
    return (vaultErrorMessages as Record<VaultError, string>)[code];
  }

  return "Error message not available in production bundles.";
}

export function isVaultError<TProgramErrorCode extends VaultError>(
  error: unknown,
  transactionMessage: {
    instructions: Record<number, { programAddress: Address }>;
  },
  code?: TProgramErrorCode,
): error is SolanaError<typeof SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM> &
  Readonly<{ context: Readonly<{ code: TProgramErrorCode }> }> {
  return isProgramError<TProgramErrorCode>(
    error,
    transactionMessage,
    VAULT_PROGRAM_ADDRESS,
    code,
  );
}
