/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertIsInstructionWithAccounts,
  containsBytes,
  fixEncoderSize,
  getBytesEncoder,
  type Address,
  type Instruction,
  type InstructionWithData,
  type ReadonlyUint8Array,
} from "@solana/kit";
import {
  parseClaimAndCommitInstruction,
  parseClaimDropInstruction,
  parseDelegateDropInstruction,
  parseDepositInstruction,
  parseInitializeDropInstruction,
  parsePayoutClaimInstruction,
  parseProcessUndelegationInstruction,
  parseUndelegateDropInstruction,
  parseWithdrawInstruction,
  type ParsedClaimAndCommitInstruction,
  type ParsedClaimDropInstruction,
  type ParsedDelegateDropInstruction,
  type ParsedDepositInstruction,
  type ParsedInitializeDropInstruction,
  type ParsedPayoutClaimInstruction,
  type ParsedProcessUndelegationInstruction,
  type ParsedUndelegateDropInstruction,
  type ParsedWithdrawInstruction,
} from "../instructions";

export const VAULT_PROGRAM_ADDRESS =
  "6mEc28x37u7281vSXg5CwcVtj2qKVX4dX1vwrQYG1RNv" as Address<"6mEc28x37u7281vSXg5CwcVtj2qKVX4dX1vwrQYG1RNv">;

export enum VaultAccount {
  Drop,
}

export function identifyVaultAccount(
  account: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): VaultAccount {
  const data = "data" in account ? account.data : account;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([56, 174, 80, 200, 182, 146, 223, 35]),
      ),
      0,
    )
  ) {
    return VaultAccount.Drop;
  }
  throw new Error(
    "The provided account could not be identified as a vault account.",
  );
}

export enum VaultInstruction {
  ClaimAndCommit,
  ClaimDrop,
  DelegateDrop,
  Deposit,
  InitializeDrop,
  PayoutClaim,
  ProcessUndelegation,
  UndelegateDrop,
  Withdraw,
}

export function identifyVaultInstruction(
  instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): VaultInstruction {
  const data = "data" in instruction ? instruction.data : instruction;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([120, 213, 50, 89, 149, 69, 89, 123]),
      ),
      0,
    )
  ) {
    return VaultInstruction.ClaimAndCommit;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([157, 29, 89, 14, 81, 203, 107, 58]),
      ),
      0,
    )
  ) {
    return VaultInstruction.ClaimDrop;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([11, 100, 172, 144, 173, 50, 195, 32]),
      ),
      0,
    )
  ) {
    return VaultInstruction.DelegateDrop;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([242, 35, 198, 137, 82, 225, 242, 182]),
      ),
      0,
    )
  ) {
    return VaultInstruction.Deposit;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([189, 174, 162, 164, 253, 144, 182, 186]),
      ),
      0,
    )
  ) {
    return VaultInstruction.InitializeDrop;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([245, 117, 170, 236, 236, 239, 99, 252]),
      ),
      0,
    )
  ) {
    return VaultInstruction.PayoutClaim;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([196, 28, 41, 206, 48, 37, 51, 167]),
      ),
      0,
    )
  ) {
    return VaultInstruction.ProcessUndelegation;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([206, 237, 229, 197, 227, 249, 58, 80]),
      ),
      0,
    )
  ) {
    return VaultInstruction.UndelegateDrop;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([183, 18, 70, 156, 148, 109, 161, 34]),
      ),
      0,
    )
  ) {
    return VaultInstruction.Withdraw;
  }
  throw new Error(
    "The provided instruction could not be identified as a vault instruction.",
  );
}

export type ParsedVaultInstruction<
  TProgram extends string = "6mEc28x37u7281vSXg5CwcVtj2qKVX4dX1vwrQYG1RNv",
> =
  | ({
      instructionType: VaultInstruction.ClaimAndCommit;
    } & ParsedClaimAndCommitInstruction<TProgram>)
  | ({
      instructionType: VaultInstruction.ClaimDrop;
    } & ParsedClaimDropInstruction<TProgram>)
  | ({
      instructionType: VaultInstruction.DelegateDrop;
    } & ParsedDelegateDropInstruction<TProgram>)
  | ({
      instructionType: VaultInstruction.Deposit;
    } & ParsedDepositInstruction<TProgram>)
  | ({
      instructionType: VaultInstruction.InitializeDrop;
    } & ParsedInitializeDropInstruction<TProgram>)
  | ({
      instructionType: VaultInstruction.PayoutClaim;
    } & ParsedPayoutClaimInstruction<TProgram>)
  | ({
      instructionType: VaultInstruction.ProcessUndelegation;
    } & ParsedProcessUndelegationInstruction<TProgram>)
  | ({
      instructionType: VaultInstruction.UndelegateDrop;
    } & ParsedUndelegateDropInstruction<TProgram>)
  | ({
      instructionType: VaultInstruction.Withdraw;
    } & ParsedWithdrawInstruction<TProgram>);

export function parseVaultInstruction<TProgram extends string>(
  instruction: Instruction<TProgram> & InstructionWithData<ReadonlyUint8Array>,
): ParsedVaultInstruction<TProgram> {
  const instructionType = identifyVaultInstruction(instruction);
  switch (instructionType) {
    case VaultInstruction.ClaimAndCommit: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: VaultInstruction.ClaimAndCommit,
        ...parseClaimAndCommitInstruction(instruction),
      };
    }
    case VaultInstruction.ClaimDrop: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: VaultInstruction.ClaimDrop,
        ...parseClaimDropInstruction(instruction),
      };
    }
    case VaultInstruction.DelegateDrop: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: VaultInstruction.DelegateDrop,
        ...parseDelegateDropInstruction(instruction),
      };
    }
    case VaultInstruction.Deposit: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: VaultInstruction.Deposit,
        ...parseDepositInstruction(instruction),
      };
    }
    case VaultInstruction.InitializeDrop: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: VaultInstruction.InitializeDrop,
        ...parseInitializeDropInstruction(instruction),
      };
    }
    case VaultInstruction.PayoutClaim: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: VaultInstruction.PayoutClaim,
        ...parsePayoutClaimInstruction(instruction),
      };
    }
    case VaultInstruction.ProcessUndelegation: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: VaultInstruction.ProcessUndelegation,
        ...parseProcessUndelegationInstruction(instruction),
      };
    }
    case VaultInstruction.UndelegateDrop: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: VaultInstruction.UndelegateDrop,
        ...parseUndelegateDropInstruction(instruction),
      };
    }
    case VaultInstruction.Withdraw: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: VaultInstruction.Withdraw,
        ...parseWithdrawInstruction(instruction),
      };
    }
    default:
      throw new Error(
        `Unrecognized instruction type: ${instructionType as string}`,
      );
  }
}
