/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { findClaimRecordPda } from "../pdas";
import { VAULT_PROGRAM_ADDRESS } from "../programs";
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from "../shared";

export const CLAIM_AND_COMMIT_DISCRIMINATOR = new Uint8Array([
  120, 213, 50, 89, 149, 69, 89, 123,
]);

export function getClaimAndCommitDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    CLAIM_AND_COMMIT_DISCRIMINATOR,
  );
}

export type ClaimAndCommitInstruction<
  TProgram extends string = typeof VAULT_PROGRAM_ADDRESS,
  TAccountPayer extends string | AccountMeta<string> = string,
  TAccountHunter extends string | AccountMeta<string> = string,
  TAccountDrop extends string | AccountMeta<string> = string,
  TAccountClaimRecord extends string | AccountMeta<string> = string,
  TAccountMagicContext extends string | AccountMeta<string> = string,
  TAccountMagicProgram extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountPayer extends string
        ? WritableSignerAccount<TAccountPayer> &
            AccountSignerMeta<TAccountPayer>
        : TAccountPayer,
      TAccountHunter extends string
        ? WritableAccount<TAccountHunter>
        : TAccountHunter,
      TAccountDrop extends string
        ? WritableAccount<TAccountDrop>
        : TAccountDrop,
      TAccountClaimRecord extends string
        ? WritableAccount<TAccountClaimRecord>
        : TAccountClaimRecord,
      TAccountMagicContext extends string
        ? ReadonlyAccount<TAccountMagicContext>
        : TAccountMagicContext,
      TAccountMagicProgram extends string
        ? ReadonlyAccount<TAccountMagicProgram>
        : TAccountMagicProgram,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type ClaimAndCommitInstructionData = {
  discriminator: ReadonlyUint8Array;
  lat: bigint;
  long: bigint;
};

export type ClaimAndCommitInstructionDataArgs = {
  lat: number | bigint;
  long: number | bigint;
};

export function getClaimAndCommitInstructionDataEncoder(): FixedSizeEncoder<ClaimAndCommitInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["lat", getI64Encoder()],
      ["long", getI64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: CLAIM_AND_COMMIT_DISCRIMINATOR }),
  );
}

export function getClaimAndCommitInstructionDataDecoder(): FixedSizeDecoder<ClaimAndCommitInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["lat", getI64Decoder()],
    ["long", getI64Decoder()],
  ]);
}

export function getClaimAndCommitInstructionDataCodec(): FixedSizeCodec<
  ClaimAndCommitInstructionDataArgs,
  ClaimAndCommitInstructionData
> {
  return combineCodec(
    getClaimAndCommitInstructionDataEncoder(),
    getClaimAndCommitInstructionDataDecoder(),
  );
}

export type ClaimAndCommitAsyncInput<
  TAccountPayer extends string = string,
  TAccountHunter extends string = string,
  TAccountDrop extends string = string,
  TAccountClaimRecord extends string = string,
  TAccountMagicContext extends string = string,
  TAccountMagicProgram extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  payer: TransactionSigner<TAccountPayer>;
  hunter: Address<TAccountHunter>;
  drop: Address<TAccountDrop>;
  claimRecord?: Address<TAccountClaimRecord>;
  magicContext: Address<TAccountMagicContext>;
  magicProgram: Address<TAccountMagicProgram>;
  systemProgram?: Address<TAccountSystemProgram>;
  lat: ClaimAndCommitInstructionDataArgs["lat"];
  long: ClaimAndCommitInstructionDataArgs["long"];
};

export async function getClaimAndCommitInstructionAsync<
  TAccountPayer extends string,
  TAccountHunter extends string,
  TAccountDrop extends string,
  TAccountClaimRecord extends string,
  TAccountMagicContext extends string,
  TAccountMagicProgram extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof VAULT_PROGRAM_ADDRESS,
>(
  input: ClaimAndCommitAsyncInput<
    TAccountPayer,
    TAccountHunter,
    TAccountDrop,
    TAccountClaimRecord,
    TAccountMagicContext,
    TAccountMagicProgram,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  ClaimAndCommitInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountHunter,
    TAccountDrop,
    TAccountClaimRecord,
    TAccountMagicContext,
    TAccountMagicProgram,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? VAULT_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    payer: { value: input.payer ?? null, isWritable: true },
    hunter: { value: input.hunter ?? null, isWritable: true },
    drop: { value: input.drop ?? null, isWritable: true },
    claimRecord: { value: input.claimRecord ?? null, isWritable: true },
    magicContext: { value: input.magicContext ?? null, isWritable: false },
    magicProgram: { value: input.magicProgram ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.claimRecord.value) {
    accounts.claimRecord.value = await findClaimRecordPda({
      drop: expectAddress(accounts.drop.value),
      hunter: expectAddress(accounts.hunter.value),
    });
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.payer),
      getAccountMeta(accounts.hunter),
      getAccountMeta(accounts.drop),
      getAccountMeta(accounts.claimRecord),
      getAccountMeta(accounts.magicContext),
      getAccountMeta(accounts.magicProgram),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getClaimAndCommitInstructionDataEncoder().encode(
      args as ClaimAndCommitInstructionDataArgs,
    ),
    programAddress,
  } as ClaimAndCommitInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountHunter,
    TAccountDrop,
    TAccountClaimRecord,
    TAccountMagicContext,
    TAccountMagicProgram,
    TAccountSystemProgram
  >);
}

export type ClaimAndCommitInput<
  TAccountPayer extends string = string,
  TAccountHunter extends string = string,
  TAccountDrop extends string = string,
  TAccountClaimRecord extends string = string,
  TAccountMagicContext extends string = string,
  TAccountMagicProgram extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  payer: TransactionSigner<TAccountPayer>;
  hunter: Address<TAccountHunter>;
  drop: Address<TAccountDrop>;
  claimRecord: Address<TAccountClaimRecord>;
  magicContext: Address<TAccountMagicContext>;
  magicProgram: Address<TAccountMagicProgram>;
  systemProgram?: Address<TAccountSystemProgram>;
  lat: ClaimAndCommitInstructionDataArgs["lat"];
  long: ClaimAndCommitInstructionDataArgs["long"];
};

export function getClaimAndCommitInstruction<
  TAccountPayer extends string,
  TAccountHunter extends string,
  TAccountDrop extends string,
  TAccountClaimRecord extends string,
  TAccountMagicContext extends string,
  TAccountMagicProgram extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof VAULT_PROGRAM_ADDRESS,
>(
  input: ClaimAndCommitInput<
    TAccountPayer,
    TAccountHunter,
    TAccountDrop,
    TAccountClaimRecord,
    TAccountMagicContext,
    TAccountMagicProgram,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): ClaimAndCommitInstruction<
  TProgramAddress,
  TAccountPayer,
  TAccountHunter,
  TAccountDrop,
  TAccountClaimRecord,
  TAccountMagicContext,
  TAccountMagicProgram,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? VAULT_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    payer: { value: input.payer ?? null, isWritable: true },
    hunter: { value: input.hunter ?? null, isWritable: true },
    drop: { value: input.drop ?? null, isWritable: true },
    claimRecord: { value: input.claimRecord ?? null, isWritable: true },
    magicContext: { value: input.magicContext ?? null, isWritable: false },
    magicProgram: { value: input.magicProgram ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.payer),
      getAccountMeta(accounts.hunter),
      getAccountMeta(accounts.drop),
      getAccountMeta(accounts.claimRecord),
      getAccountMeta(accounts.magicContext),
      getAccountMeta(accounts.magicProgram),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getClaimAndCommitInstructionDataEncoder().encode(
      args as ClaimAndCommitInstructionDataArgs,
    ),
    programAddress,
  } as ClaimAndCommitInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountHunter,
    TAccountDrop,
    TAccountClaimRecord,
    TAccountMagicContext,
    TAccountMagicProgram,
    TAccountSystemProgram
  >);
}

export type ParsedClaimAndCommitInstruction<
  TProgram extends string = typeof VAULT_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    payer: TAccountMetas[0];
    hunter: TAccountMetas[1];
    drop: TAccountMetas[2];
    claimRecord: TAccountMetas[3];
    magicContext: TAccountMetas[4];
    magicProgram: TAccountMetas[5];
    systemProgram: TAccountMetas[6];
  };
  data: ClaimAndCommitInstructionData;
};

export function parseClaimAndCommitInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedClaimAndCommitInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 7) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      payer: getNextAccount(),
      hunter: getNextAccount(),
      drop: getNextAccount(),
      claimRecord: getNextAccount(),
      magicContext: getNextAccount(),
      magicProgram: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getClaimAndCommitInstructionDataDecoder().decode(instruction.data),
  };
}
