/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { VAULT_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";

export const CLAIM_DROP_DISCRIMINATOR = new Uint8Array([
  157, 29, 89, 14, 81, 203, 107, 58,
]);

export function getClaimDropDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(CLAIM_DROP_DISCRIMINATOR);
}

export type ClaimDropInstruction<
  TProgram extends string = typeof VAULT_PROGRAM_ADDRESS,
  TAccountHunter extends string | AccountMeta<string> = string,
  TAccountBackendAuthority extends string | AccountMeta<string> = string,
  TAccountDrop extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountHunter extends string
        ? WritableSignerAccount<TAccountHunter> &
            AccountSignerMeta<TAccountHunter>
        : TAccountHunter,
      TAccountBackendAuthority extends string
        ? ReadonlySignerAccount<TAccountBackendAuthority> &
            AccountSignerMeta<TAccountBackendAuthority>
        : TAccountBackendAuthority,
      TAccountDrop extends string
        ? WritableAccount<TAccountDrop>
        : TAccountDrop,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type ClaimDropInstructionData = {
  discriminator: ReadonlyUint8Array;
  lat: bigint;
  long: bigint;
};

export type ClaimDropInstructionDataArgs = {
  lat: number | bigint;
  long: number | bigint;
};

export function getClaimDropInstructionDataEncoder(): FixedSizeEncoder<ClaimDropInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["lat", getI64Encoder()],
      ["long", getI64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: CLAIM_DROP_DISCRIMINATOR })
  );
}

export function getClaimDropInstructionDataDecoder(): FixedSizeDecoder<ClaimDropInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["lat", getI64Decoder()],
    ["long", getI64Decoder()],
  ]);
}

export function getClaimDropInstructionDataCodec(): FixedSizeCodec<
  ClaimDropInstructionDataArgs,
  ClaimDropInstructionData
> {
  return combineCodec(
    getClaimDropInstructionDataEncoder(),
    getClaimDropInstructionDataDecoder()
  );
}

export type ClaimDropInput<
  TAccountHunter extends string = string,
  TAccountBackendAuthority extends string = string,
  TAccountDrop extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  hunter: TransactionSigner<TAccountHunter>;
  backendAuthority: TransactionSigner<TAccountBackendAuthority>;
  drop: Address<TAccountDrop>;
  systemProgram?: Address<TAccountSystemProgram>;
  lat: ClaimDropInstructionDataArgs["lat"];
  long: ClaimDropInstructionDataArgs["long"];
};

export function getClaimDropInstruction<
  TAccountHunter extends string,
  TAccountBackendAuthority extends string,
  TAccountDrop extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof VAULT_PROGRAM_ADDRESS,
>(
  input: ClaimDropInput<
    TAccountHunter,
    TAccountBackendAuthority,
    TAccountDrop,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): ClaimDropInstruction<
  TProgramAddress,
  TAccountHunter,
  TAccountBackendAuthority,
  TAccountDrop,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? VAULT_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    hunter: { value: input.hunter ?? null, isWritable: true },
    backendAuthority: {
      value: input.backendAuthority ?? null,
      isWritable: false,
    },
    drop: { value: input.drop ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.hunter),
      getAccountMeta(accounts.backendAuthority),
      getAccountMeta(accounts.drop),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getClaimDropInstructionDataEncoder().encode(
      args as ClaimDropInstructionDataArgs
    ),
    programAddress,
  } as ClaimDropInstruction<
    TProgramAddress,
    TAccountHunter,
    TAccountBackendAuthority,
    TAccountDrop,
    TAccountSystemProgram
  >);
}

export type ParsedClaimDropInstruction<
  TProgram extends string = typeof VAULT_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    hunter: TAccountMetas[0];
    backendAuthority: TAccountMetas[1];
    drop: TAccountMetas[2];
    systemProgram: TAccountMetas[3];
  };
  data: ClaimDropInstructionData;
};

export function parseClaimDropInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedClaimDropInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 4) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      hunter: getNextAccount(),
      backendAuthority: getNextAccount(),
      drop: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getClaimDropInstructionDataDecoder().decode(instruction.data),
  };
}
