/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  findBufferPdaPda,
  findDelegationMetadataPdaPda,
  findDelegationRecordPdaPda,
} from "../pdas";
import { VAULT_PROGRAM_ADDRESS } from "../programs";
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from "../shared";

export const DELEGATE_DROP_DISCRIMINATOR = new Uint8Array([
  11, 100, 172, 144, 173, 50, 195, 32,
]);

export function getDelegateDropDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    DELEGATE_DROP_DISCRIMINATOR,
  );
}

export type DelegateDropInstruction<
  TProgram extends string = typeof VAULT_PROGRAM_ADDRESS,
  TAccountPayer extends string | AccountMeta<string> = string,
  TAccountBufferPda extends string | AccountMeta<string> = string,
  TAccountDelegationRecordPda extends string | AccountMeta<string> = string,
  TAccountDelegationMetadataPda extends string | AccountMeta<string> = string,
  TAccountPda extends string | AccountMeta<string> = string,
  TAccountOwnerProgram extends string | AccountMeta<string> =
    "6mEc28x37u7281vSXg5CwcVtj2qKVX4dX1vwrQYG1RNv",
  TAccountDelegationProgram extends string | AccountMeta<string> =
    "DELeGGvXpWV2fqJUhqcF5ZSYMS4JTLjteaAMARRSaeSh",
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountPayer extends string
        ? WritableSignerAccount<TAccountPayer> &
            AccountSignerMeta<TAccountPayer>
        : TAccountPayer,
      TAccountBufferPda extends string
        ? WritableAccount<TAccountBufferPda>
        : TAccountBufferPda,
      TAccountDelegationRecordPda extends string
        ? WritableAccount<TAccountDelegationRecordPda>
        : TAccountDelegationRecordPda,
      TAccountDelegationMetadataPda extends string
        ? WritableAccount<TAccountDelegationMetadataPda>
        : TAccountDelegationMetadataPda,
      TAccountPda extends string ? WritableAccount<TAccountPda> : TAccountPda,
      TAccountOwnerProgram extends string
        ? ReadonlyAccount<TAccountOwnerProgram>
        : TAccountOwnerProgram,
      TAccountDelegationProgram extends string
        ? ReadonlyAccount<TAccountDelegationProgram>
        : TAccountDelegationProgram,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type DelegateDropInstructionData = {
  discriminator: ReadonlyUint8Array;
  sponsor: Address;
  campaignId: ReadonlyUint8Array;
};

export type DelegateDropInstructionDataArgs = {
  sponsor: Address;
  campaignId: ReadonlyUint8Array;
};

export function getDelegateDropInstructionDataEncoder(): FixedSizeEncoder<DelegateDropInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["sponsor", getAddressEncoder()],
      ["campaignId", fixEncoderSize(getBytesEncoder(), 8)],
    ]),
    (value) => ({ ...value, discriminator: DELEGATE_DROP_DISCRIMINATOR }),
  );
}

export function getDelegateDropInstructionDataDecoder(): FixedSizeDecoder<DelegateDropInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["sponsor", getAddressDecoder()],
    ["campaignId", fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getDelegateDropInstructionDataCodec(): FixedSizeCodec<
  DelegateDropInstructionDataArgs,
  DelegateDropInstructionData
> {
  return combineCodec(
    getDelegateDropInstructionDataEncoder(),
    getDelegateDropInstructionDataDecoder(),
  );
}

export type DelegateDropAsyncInput<
  TAccountPayer extends string = string,
  TAccountBufferPda extends string = string,
  TAccountDelegationRecordPda extends string = string,
  TAccountDelegationMetadataPda extends string = string,
  TAccountPda extends string = string,
  TAccountOwnerProgram extends string = string,
  TAccountDelegationProgram extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  payer: TransactionSigner<TAccountPayer>;
  bufferPda?: Address<TAccountBufferPda>;
  delegationRecordPda?: Address<TAccountDelegationRecordPda>;
  delegationMetadataPda?: Address<TAccountDelegationMetadataPda>;
  pda: Address<TAccountPda>;
  ownerProgram?: Address<TAccountOwnerProgram>;
  delegationProgram?: Address<TAccountDelegationProgram>;
  systemProgram?: Address<TAccountSystemProgram>;
  sponsor: DelegateDropInstructionDataArgs["sponsor"];
  campaignId: DelegateDropInstructionDataArgs["campaignId"];
};

export async function getDelegateDropInstructionAsync<
  TAccountPayer extends string,
  TAccountBufferPda extends string,
  TAccountDelegationRecordPda extends string,
  TAccountDelegationMetadataPda extends string,
  TAccountPda extends string,
  TAccountOwnerProgram extends string,
  TAccountDelegationProgram extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof VAULT_PROGRAM_ADDRESS,
>(
  input: DelegateDropAsyncInput<
    TAccountPayer,
    TAccountBufferPda,
    TAccountDelegationRecordPda,
    TAccountDelegationMetadataPda,
    TAccountPda,
    TAccountOwnerProgram,
    TAccountDelegationProgram,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  DelegateDropInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountBufferPda,
    TAccountDelegationRecordPda,
    TAccountDelegationMetadataPda,
    TAccountPda,
    TAccountOwnerProgram,
    TAccountDelegationProgram,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? VAULT_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    payer: { value: input.payer ?? null, isWritable: true },
    bufferPda: { value: input.bufferPda ?? null, isWritable: true },
    delegationRecordPda: {
      value: input.delegationRecordPda ?? null,
      isWritable: true,
    },
    delegationMetadataPda: {
      value: input.delegationMetadataPda ?? null,
      isWritable: true,
    },
    pda: { value: input.pda ?? null, isWritable: true },
    ownerProgram: { value: input.ownerProgram ?? null, isWritable: false },
    delegationProgram: {
      value: input.delegationProgram ?? null,
      isWritable: false,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.bufferPda.value) {
    accounts.bufferPda.value = await findBufferPdaPda({
      pda: expectAddress(accounts.pda.value),
    });
  }
  if (!accounts.delegationRecordPda.value) {
    accounts.delegationRecordPda.value = await findDelegationRecordPdaPda({
      pda: expectAddress(accounts.pda.value),
    });
  }
  if (!accounts.delegationMetadataPda.value) {
    accounts.delegationMetadataPda.value = await findDelegationMetadataPdaPda({
      pda: expectAddress(accounts.pda.value),
    });
  }
  if (!accounts.ownerProgram.value) {
    accounts.ownerProgram.value =
      "6mEc28x37u7281vSXg5CwcVtj2qKVX4dX1vwrQYG1RNv" as Address<"6mEc28x37u7281vSXg5CwcVtj2qKVX4dX1vwrQYG1RNv">;
  }
  if (!accounts.delegationProgram.value) {
    accounts.delegationProgram.value =
      "DELeGGvXpWV2fqJUhqcF5ZSYMS4JTLjteaAMARRSaeSh" as Address<"DELeGGvXpWV2fqJUhqcF5ZSYMS4JTLjteaAMARRSaeSh">;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.payer),
      getAccountMeta(accounts.bufferPda),
      getAccountMeta(accounts.delegationRecordPda),
      getAccountMeta(accounts.delegationMetadataPda),
      getAccountMeta(accounts.pda),
      getAccountMeta(accounts.ownerProgram),
      getAccountMeta(accounts.delegationProgram),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getDelegateDropInstructionDataEncoder().encode(
      args as DelegateDropInstructionDataArgs,
    ),
    programAddress,
  } as DelegateDropInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountBufferPda,
    TAccountDelegationRecordPda,
    TAccountDelegationMetadataPda,
    TAccountPda,
    TAccountOwnerProgram,
    TAccountDelegationProgram,
    TAccountSystemProgram
  >);
}

export type DelegateDropInput<
  TAccountPayer extends string = string,
  TAccountBufferPda extends string = string,
  TAccountDelegationRecordPda extends string = string,
  TAccountDelegationMetadataPda extends string = string,
  TAccountPda extends string = string,
  TAccountOwnerProgram extends string = string,
  TAccountDelegationProgram extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  payer: TransactionSigner<TAccountPayer>;
  bufferPda: Address<TAccountBufferPda>;
  delegationRecordPda: Address<TAccountDelegationRecordPda>;
  delegationMetadataPda: Address<TAccountDelegationMetadataPda>;
  pda: Address<TAccountPda>;
  ownerProgram?: Address<TAccountOwnerProgram>;
  delegationProgram?: Address<TAccountDelegationProgram>;
  systemProgram?: Address<TAccountSystemProgram>;
  sponsor: DelegateDropInstructionDataArgs["sponsor"];
  campaignId: DelegateDropInstructionDataArgs["campaignId"];
};

export function getDelegateDropInstruction<
  TAccountPayer extends string,
  TAccountBufferPda extends string,
  TAccountDelegationRecordPda extends string,
  TAccountDelegationMetadataPda extends string,
  TAccountPda extends string,
  TAccountOwnerProgram extends string,
  TAccountDelegationProgram extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof VAULT_PROGRAM_ADDRESS,
>(
  input: DelegateDropInput<
    TAccountPayer,
    TAccountBufferPda,
    TAccountDelegationRecordPda,
    TAccountDelegationMetadataPda,
    TAccountPda,
    TAccountOwnerProgram,
    TAccountDelegationProgram,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): DelegateDropInstruction<
  TProgramAddress,
  TAccountPayer,
  TAccountBufferPda,
  TAccountDelegationRecordPda,
  TAccountDelegationMetadataPda,
  TAccountPda,
  TAccountOwnerProgram,
  TAccountDelegationProgram,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? VAULT_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    payer: { value: input.payer ?? null, isWritable: true },
    bufferPda: { value: input.bufferPda ?? null, isWritable: true },
    delegationRecordPda: {
      value: input.delegationRecordPda ?? null,
      isWritable: true,
    },
    delegationMetadataPda: {
      value: input.delegationMetadataPda ?? null,
      isWritable: true,
    },
    pda: { value: input.pda ?? null, isWritable: true },
    ownerProgram: { value: input.ownerProgram ?? null, isWritable: false },
    delegationProgram: {
      value: input.delegationProgram ?? null,
      isWritable: false,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.ownerProgram.value) {
    accounts.ownerProgram.value =
      "6mEc28x37u7281vSXg5CwcVtj2qKVX4dX1vwrQYG1RNv" as Address<"6mEc28x37u7281vSXg5CwcVtj2qKVX4dX1vwrQYG1RNv">;
  }
  if (!accounts.delegationProgram.value) {
    accounts.delegationProgram.value =
      "DELeGGvXpWV2fqJUhqcF5ZSYMS4JTLjteaAMARRSaeSh" as Address<"DELeGGvXpWV2fqJUhqcF5ZSYMS4JTLjteaAMARRSaeSh">;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.payer),
      getAccountMeta(accounts.bufferPda),
      getAccountMeta(accounts.delegationRecordPda),
      getAccountMeta(accounts.delegationMetadataPda),
      getAccountMeta(accounts.pda),
      getAccountMeta(accounts.ownerProgram),
      getAccountMeta(accounts.delegationProgram),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getDelegateDropInstructionDataEncoder().encode(
      args as DelegateDropInstructionDataArgs,
    ),
    programAddress,
  } as DelegateDropInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountBufferPda,
    TAccountDelegationRecordPda,
    TAccountDelegationMetadataPda,
    TAccountPda,
    TAccountOwnerProgram,
    TAccountDelegationProgram,
    TAccountSystemProgram
  >);
}

export type ParsedDelegateDropInstruction<
  TProgram extends string = typeof VAULT_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    payer: TAccountMetas[0];
    bufferPda: TAccountMetas[1];
    delegationRecordPda: TAccountMetas[2];
    delegationMetadataPda: TAccountMetas[3];
    pda: TAccountMetas[4];
    ownerProgram: TAccountMetas[5];
    delegationProgram: TAccountMetas[6];
    systemProgram: TAccountMetas[7];
  };
  data: DelegateDropInstructionData;
};

export function parseDelegateDropInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedDelegateDropInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 8) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      payer: getNextAccount(),
      bufferPda: getNextAccount(),
      delegationRecordPda: getNextAccount(),
      delegationMetadataPda: getNextAccount(),
      pda: getNextAccount(),
      ownerProgram: getNextAccount(),
      delegationProgram: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getDelegateDropInstructionDataDecoder().decode(instruction.data),
  };
}
