/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { findDropPda } from "../pdas";
import { VAULT_PROGRAM_ADDRESS } from "../programs";
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from "../shared";

export const INITIALIZE_DROP_DISCRIMINATOR = new Uint8Array([
  189, 174, 162, 164, 253, 144, 182, 186,
]);

export function getInitializeDropDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    INITIALIZE_DROP_DISCRIMINATOR
  );
}

export type InitializeDropInstruction<
  TProgram extends string = typeof VAULT_PROGRAM_ADDRESS,
  TAccountSponsor extends string | AccountMeta<string> = string,
  TAccountDrop extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountSponsor extends string
        ? WritableSignerAccount<TAccountSponsor> &
            AccountSignerMeta<TAccountSponsor>
        : TAccountSponsor,
      TAccountDrop extends string
        ? WritableAccount<TAccountDrop>
        : TAccountDrop,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type InitializeDropInstructionData = {
  discriminator: ReadonlyUint8Array;
  backendAuthority: Address;
  lat: bigint;
  long: bigint;
  radius: bigint;
  amount: bigint;
};

export type InitializeDropInstructionDataArgs = {
  backendAuthority: Address;
  lat: number | bigint;
  long: number | bigint;
  radius: number | bigint;
  amount: number | bigint;
};

export function getInitializeDropInstructionDataEncoder(): FixedSizeEncoder<InitializeDropInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["backendAuthority", getAddressEncoder()],
      ["lat", getI64Encoder()],
      ["long", getI64Encoder()],
      ["radius", getU64Encoder()],
      ["amount", getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: INITIALIZE_DROP_DISCRIMINATOR })
  );
}

export function getInitializeDropInstructionDataDecoder(): FixedSizeDecoder<InitializeDropInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["backendAuthority", getAddressDecoder()],
    ["lat", getI64Decoder()],
    ["long", getI64Decoder()],
    ["radius", getU64Decoder()],
    ["amount", getU64Decoder()],
  ]);
}

export function getInitializeDropInstructionDataCodec(): FixedSizeCodec<
  InitializeDropInstructionDataArgs,
  InitializeDropInstructionData
> {
  return combineCodec(
    getInitializeDropInstructionDataEncoder(),
    getInitializeDropInstructionDataDecoder()
  );
}

export type InitializeDropAsyncInput<
  TAccountSponsor extends string = string,
  TAccountDrop extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  sponsor: TransactionSigner<TAccountSponsor>;
  drop?: Address<TAccountDrop>;
  systemProgram?: Address<TAccountSystemProgram>;
  backendAuthority: InitializeDropInstructionDataArgs["backendAuthority"];
  lat: InitializeDropInstructionDataArgs["lat"];
  long: InitializeDropInstructionDataArgs["long"];
  radius: InitializeDropInstructionDataArgs["radius"];
  amount: InitializeDropInstructionDataArgs["amount"];
};

export async function getInitializeDropInstructionAsync<
  TAccountSponsor extends string,
  TAccountDrop extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof VAULT_PROGRAM_ADDRESS,
>(
  input: InitializeDropAsyncInput<
    TAccountSponsor,
    TAccountDrop,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): Promise<
  InitializeDropInstruction<
    TProgramAddress,
    TAccountSponsor,
    TAccountDrop,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? VAULT_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    sponsor: { value: input.sponsor ?? null, isWritable: true },
    drop: { value: input.drop ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.drop.value) {
    accounts.drop.value = await findDropPda({
      sponsor: expectAddress(accounts.sponsor.value),
    });
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.sponsor),
      getAccountMeta(accounts.drop),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getInitializeDropInstructionDataEncoder().encode(
      args as InitializeDropInstructionDataArgs
    ),
    programAddress,
  } as InitializeDropInstruction<
    TProgramAddress,
    TAccountSponsor,
    TAccountDrop,
    TAccountSystemProgram
  >);
}

export type InitializeDropInput<
  TAccountSponsor extends string = string,
  TAccountDrop extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  sponsor: TransactionSigner<TAccountSponsor>;
  drop: Address<TAccountDrop>;
  systemProgram?: Address<TAccountSystemProgram>;
  backendAuthority: InitializeDropInstructionDataArgs["backendAuthority"];
  lat: InitializeDropInstructionDataArgs["lat"];
  long: InitializeDropInstructionDataArgs["long"];
  radius: InitializeDropInstructionDataArgs["radius"];
  amount: InitializeDropInstructionDataArgs["amount"];
};

export function getInitializeDropInstruction<
  TAccountSponsor extends string,
  TAccountDrop extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof VAULT_PROGRAM_ADDRESS,
>(
  input: InitializeDropInput<
    TAccountSponsor,
    TAccountDrop,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): InitializeDropInstruction<
  TProgramAddress,
  TAccountSponsor,
  TAccountDrop,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? VAULT_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    sponsor: { value: input.sponsor ?? null, isWritable: true },
    drop: { value: input.drop ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.sponsor),
      getAccountMeta(accounts.drop),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getInitializeDropInstructionDataEncoder().encode(
      args as InitializeDropInstructionDataArgs
    ),
    programAddress,
  } as InitializeDropInstruction<
    TProgramAddress,
    TAccountSponsor,
    TAccountDrop,
    TAccountSystemProgram
  >);
}

export type ParsedInitializeDropInstruction<
  TProgram extends string = typeof VAULT_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    sponsor: TAccountMetas[0];
    drop: TAccountMetas[1];
    systemProgram: TAccountMetas[2];
  };
  data: InitializeDropInstructionData;
};

export function parseInitializeDropInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedInitializeDropInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      sponsor: getNextAccount(),
      drop: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getInitializeDropInstructionDataDecoder().decode(instruction.data),
  };
}
