/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type WritableAccount,
} from "@solana/kit";
import { VAULT_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";

export const PAYOUT_CLAIM_DISCRIMINATOR = new Uint8Array([
  245, 117, 170, 236, 236, 239, 99, 252,
]);

export function getPayoutClaimDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    PAYOUT_CLAIM_DISCRIMINATOR,
  );
}

export type PayoutClaimInstruction<
  TProgram extends string = typeof VAULT_PROGRAM_ADDRESS,
  TAccountDrop extends string | AccountMeta<string> = string,
  TAccountHunter extends string | AccountMeta<string> = string,
  TAccountEscrowAuth extends string | AccountMeta<string> = string,
  TAccountEscrow extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountDrop extends string
        ? WritableAccount<TAccountDrop>
        : TAccountDrop,
      TAccountHunter extends string
        ? WritableAccount<TAccountHunter>
        : TAccountHunter,
      TAccountEscrowAuth extends string
        ? ReadonlyAccount<TAccountEscrowAuth>
        : TAccountEscrowAuth,
      TAccountEscrow extends string
        ? ReadonlyAccount<TAccountEscrow>
        : TAccountEscrow,
      ...TRemainingAccounts,
    ]
  >;

export type PayoutClaimInstructionData = {
  discriminator: ReadonlyUint8Array;
  hunter: Address;
};

export type PayoutClaimInstructionDataArgs = { hunter: Address };

export function getPayoutClaimInstructionDataEncoder(): FixedSizeEncoder<PayoutClaimInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["hunter", getAddressEncoder()],
    ]),
    (value) => ({ ...value, discriminator: PAYOUT_CLAIM_DISCRIMINATOR }),
  );
}

export function getPayoutClaimInstructionDataDecoder(): FixedSizeDecoder<PayoutClaimInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["hunter", getAddressDecoder()],
  ]);
}

export function getPayoutClaimInstructionDataCodec(): FixedSizeCodec<
  PayoutClaimInstructionDataArgs,
  PayoutClaimInstructionData
> {
  return combineCodec(
    getPayoutClaimInstructionDataEncoder(),
    getPayoutClaimInstructionDataDecoder(),
  );
}

export type PayoutClaimInput<
  TAccountDrop extends string = string,
  TAccountHunter extends string = string,
  TAccountEscrowAuth extends string = string,
  TAccountEscrow extends string = string,
> = {
  drop: Address<TAccountDrop>;
  hunter: Address<TAccountHunter>;
  escrowAuth: Address<TAccountEscrowAuth>;
  escrow: Address<TAccountEscrow>;
  hunterArg: PayoutClaimInstructionDataArgs["hunter"];
};

export function getPayoutClaimInstruction<
  TAccountDrop extends string,
  TAccountHunter extends string,
  TAccountEscrowAuth extends string,
  TAccountEscrow extends string,
  TProgramAddress extends Address = typeof VAULT_PROGRAM_ADDRESS,
>(
  input: PayoutClaimInput<
    TAccountDrop,
    TAccountHunter,
    TAccountEscrowAuth,
    TAccountEscrow
  >,
  config?: { programAddress?: TProgramAddress },
): PayoutClaimInstruction<
  TProgramAddress,
  TAccountDrop,
  TAccountHunter,
  TAccountEscrowAuth,
  TAccountEscrow
> {
  // Program address.
  const programAddress = config?.programAddress ?? VAULT_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    drop: { value: input.drop ?? null, isWritable: true },
    hunter: { value: input.hunter ?? null, isWritable: true },
    escrowAuth: { value: input.escrowAuth ?? null, isWritable: false },
    escrow: { value: input.escrow ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input, hunter: input.hunterArg };

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.drop),
      getAccountMeta(accounts.hunter),
      getAccountMeta(accounts.escrowAuth),
      getAccountMeta(accounts.escrow),
    ],
    data: getPayoutClaimInstructionDataEncoder().encode(
      args as PayoutClaimInstructionDataArgs,
    ),
    programAddress,
  } as PayoutClaimInstruction<
    TProgramAddress,
    TAccountDrop,
    TAccountHunter,
    TAccountEscrowAuth,
    TAccountEscrow
  >);
}

export type ParsedPayoutClaimInstruction<
  TProgram extends string = typeof VAULT_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    drop: TAccountMetas[0];
    hunter: TAccountMetas[1];
    escrowAuth: TAccountMetas[2];
    escrow: TAccountMetas[3];
  };
  data: PayoutClaimInstructionData;
};

export function parsePayoutClaimInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedPayoutClaimInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 4) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      drop: getNextAccount(),
      hunter: getNextAccount(),
      escrowAuth: getNextAccount(),
      escrow: getNextAccount(),
    },
    data: getPayoutClaimInstructionDataDecoder().decode(instruction.data),
  };
}
