/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { VAULT_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";

export const UNDELEGATE_DROP_DISCRIMINATOR = new Uint8Array([
  206, 237, 229, 197, 227, 249, 58, 80,
]);

export function getUndelegateDropDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    UNDELEGATE_DROP_DISCRIMINATOR,
  );
}

export type UndelegateDropInstruction<
  TProgram extends string = typeof VAULT_PROGRAM_ADDRESS,
  TAccountPayer extends string | AccountMeta<string> = string,
  TAccountDrop extends string | AccountMeta<string> = string,
  TAccountMagicContext extends string | AccountMeta<string> = string,
  TAccountMagicProgram extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountPayer extends string
        ? WritableSignerAccount<TAccountPayer> &
            AccountSignerMeta<TAccountPayer>
        : TAccountPayer,
      TAccountDrop extends string
        ? WritableAccount<TAccountDrop>
        : TAccountDrop,
      TAccountMagicContext extends string
        ? ReadonlyAccount<TAccountMagicContext>
        : TAccountMagicContext,
      TAccountMagicProgram extends string
        ? ReadonlyAccount<TAccountMagicProgram>
        : TAccountMagicProgram,
      ...TRemainingAccounts,
    ]
  >;

export type UndelegateDropInstructionData = {
  discriminator: ReadonlyUint8Array;
};

export type UndelegateDropInstructionDataArgs = {};

export function getUndelegateDropInstructionDataEncoder(): FixedSizeEncoder<UndelegateDropInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([["discriminator", fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: UNDELEGATE_DROP_DISCRIMINATOR }),
  );
}

export function getUndelegateDropInstructionDataDecoder(): FixedSizeDecoder<UndelegateDropInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getUndelegateDropInstructionDataCodec(): FixedSizeCodec<
  UndelegateDropInstructionDataArgs,
  UndelegateDropInstructionData
> {
  return combineCodec(
    getUndelegateDropInstructionDataEncoder(),
    getUndelegateDropInstructionDataDecoder(),
  );
}

export type UndelegateDropInput<
  TAccountPayer extends string = string,
  TAccountDrop extends string = string,
  TAccountMagicContext extends string = string,
  TAccountMagicProgram extends string = string,
> = {
  payer: TransactionSigner<TAccountPayer>;
  drop: Address<TAccountDrop>;
  magicContext: Address<TAccountMagicContext>;
  magicProgram: Address<TAccountMagicProgram>;
};

export function getUndelegateDropInstruction<
  TAccountPayer extends string,
  TAccountDrop extends string,
  TAccountMagicContext extends string,
  TAccountMagicProgram extends string,
  TProgramAddress extends Address = typeof VAULT_PROGRAM_ADDRESS,
>(
  input: UndelegateDropInput<
    TAccountPayer,
    TAccountDrop,
    TAccountMagicContext,
    TAccountMagicProgram
  >,
  config?: { programAddress?: TProgramAddress },
): UndelegateDropInstruction<
  TProgramAddress,
  TAccountPayer,
  TAccountDrop,
  TAccountMagicContext,
  TAccountMagicProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? VAULT_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    payer: { value: input.payer ?? null, isWritable: true },
    drop: { value: input.drop ?? null, isWritable: true },
    magicContext: { value: input.magicContext ?? null, isWritable: false },
    magicProgram: { value: input.magicProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.payer),
      getAccountMeta(accounts.drop),
      getAccountMeta(accounts.magicContext),
      getAccountMeta(accounts.magicProgram),
    ],
    data: getUndelegateDropInstructionDataEncoder().encode({}),
    programAddress,
  } as UndelegateDropInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountDrop,
    TAccountMagicContext,
    TAccountMagicProgram
  >);
}

export type ParsedUndelegateDropInstruction<
  TProgram extends string = typeof VAULT_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    payer: TAccountMetas[0];
    drop: TAccountMetas[1];
    magicContext: TAccountMetas[2];
    magicProgram: TAccountMetas[3];
  };
  data: UndelegateDropInstructionData;
};

export function parseUndelegateDropInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedUndelegateDropInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 4) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      payer: getNextAccount(),
      drop: getNextAccount(),
      magicContext: getNextAccount(),
      magicProgram: getNextAccount(),
    },
    data: getUndelegateDropInstructionDataDecoder().decode(instruction.data),
  };
}
