/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  getAddressEncoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  type Address,
  type ProgramDerivedAddress,
} from "@solana/kit";

export type DelegationRecordPdaSeeds = {
  pda: Address;
};

export async function findDelegationRecordPdaPda(
  seeds: DelegationRecordPdaSeeds,
  config: { programAddress?: Address | undefined } = {},
): Promise<ProgramDerivedAddress> {
  const {
    programAddress = "6mEc28x37u7281vSXg5CwcVtj2qKVX4dX1vwrQYG1RNv" as Address<"6mEc28x37u7281vSXg5CwcVtj2qKVX4dX1vwrQYG1RNv">,
  } = config;
  return await getProgramDerivedAddress({
    programAddress,
    seeds: [
      getBytesEncoder().encode(
        new Uint8Array([100, 101, 108, 101, 103, 97, 116, 105, 111, 110]),
      ),
      getAddressEncoder().encode(seeds.pda),
    ],
  });
}
