/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";

export const DROP_DISCRIMINATOR = new Uint8Array([
  56, 174, 80, 200, 182, 146, 223, 35,
]);

export function getDropDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(DROP_DISCRIMINATOR);
}

export type Drop = {
  discriminator: ReadonlyUint8Array;
  sponsor: Address;
  backendAuthority: Address;
  latitude: bigint;
  longitude: bigint;
  radius: bigint;
  amount: bigint;
};

export type DropArgs = {
  sponsor: Address;
  backendAuthority: Address;
  latitude: number | bigint;
  longitude: number | bigint;
  radius: number | bigint;
  amount: number | bigint;
};

/** Gets the encoder for {@link DropArgs} account data. */
export function getDropEncoder(): FixedSizeEncoder<DropArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["sponsor", getAddressEncoder()],
      ["backendAuthority", getAddressEncoder()],
      ["latitude", getI64Encoder()],
      ["longitude", getI64Encoder()],
      ["radius", getU64Encoder()],
      ["amount", getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: DROP_DISCRIMINATOR }),
  );
}

/** Gets the decoder for {@link Drop} account data. */
export function getDropDecoder(): FixedSizeDecoder<Drop> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["sponsor", getAddressDecoder()],
    ["backendAuthority", getAddressDecoder()],
    ["latitude", getI64Decoder()],
    ["longitude", getI64Decoder()],
    ["radius", getU64Decoder()],
    ["amount", getU64Decoder()],
  ]);
}

/** Gets the codec for {@link Drop} account data. */
export function getDropCodec(): FixedSizeCodec<DropArgs, Drop> {
  return combineCodec(getDropEncoder(), getDropDecoder());
}

export function decodeDrop<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<Drop, TAddress>;
export function decodeDrop<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<Drop, TAddress>;
export function decodeDrop<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
): Account<Drop, TAddress> | MaybeAccount<Drop, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getDropDecoder(),
  );
}

export async function fetchDrop<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<Drop, TAddress>> {
  const maybeAccount = await fetchMaybeDrop(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeDrop<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<Drop, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeDrop(maybeAccount);
}

export async function fetchAllDrop(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<Drop>[]> {
  const maybeAccounts = await fetchAllMaybeDrop(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeDrop(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<Drop>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeDrop(maybeAccount));
}

export function getDropSize(): number {
  return 104;
}
